/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.cptdemo;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.*;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Edna
 */
public class MainMenuDemo extends javax.swing.JFrame {
    
    // Variables
    private javax.swing.JPanel p;

    String PriceText = "";
    String InvText = "";
    String PriceHeader;
    String price;
    int i;

    FileReader in;
    BufferedReader readFile;
    String lineOfText;
 //   String File = "StockList.txt";
    String[] inventory;
    
    String csvFile = "StockList.csv";
    String line = "";
    String cvsSplitBy = ",";
        
    DefaultListModel model1 = new DefaultListModel();
    List<Item> ItemList = new ArrayList<Item>();
    
    // Format numeric values to two decimal places and currency
    public static NumberFormat money = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form MainMenuDemo
     */
    public MainMenuDemo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonsPanel = new javax.swing.JPanel();
        DispInvButton = new javax.swing.JButton();
        EditInvButton = new javax.swing.JButton();
        DispPricesButton = new javax.swing.JButton();
        EditPricesButton = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        WelcomeWindow = new javax.swing.JPanel();
        jLabelWW = new javax.swing.JLabel();
        WelcDispInvButton = new javax.swing.JButton();
        WelcEditInvButton = new javax.swing.JButton();
        WelcDispPricesButton = new javax.swing.JButton();
        WelcEditPricesButton = new javax.swing.JButton();
        DisplayPrices = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDP = new javax.swing.JTextArea();
        jLabelDP = new javax.swing.JLabel();
        DisplayInventory = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDis = new javax.swing.JTextArea();
        EditInv = new javax.swing.JPanel();
        EditInvLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditInvList = new javax.swing.JList<String>();
        EditPrices = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditPriceList = new javax.swing.JList();
        SelectItemButton = new javax.swing.JButton();
        jProductLabel = new javax.swing.JLabel();
        ProdTextField = new javax.swing.JTextField();
        jPriceLabel = new javax.swing.JLabel();
        PriceTextField = new javax.swing.JTextField();
        SavePriceButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DispInvButton.setText("Display Inventory");
        DispInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispInvButtonActionPerformed(evt);
            }
        });

        EditInvButton.setText("Edit Inventory");
        EditInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInvButtonActionPerformed(evt);
            }
        });

        DispPricesButton.setText("Display Prices");
        DispPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPricesButtonActionPerformed(evt);
            }
        });

        EditPricesButton.setText("Edit Prices");
        EditPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPricesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DispInvButton))
                    .addComponent(EditInvButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DispPricesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditPricesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(DispInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(DispPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(255, 51, 255));
        DynamicPanel.setLayout(new java.awt.CardLayout());

        WelcomeWindow.setBackground(new java.awt.Color(153, 255, 255));

        jLabelWW.setFont(new java.awt.Font("Lemon/Milk", 0, 24)); // NOI18N
        jLabelWW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWW.setText("Tuck 'N' Roll");

        WelcDispInvButton.setText("Display Inventory");
        WelcDispInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcDispInvButtonActionPerformed(evt);
            }
        });

        WelcEditInvButton.setText("Edit Inventory");
        WelcEditInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcEditInvButtonActionPerformed(evt);
            }
        });

        WelcDispPricesButton.setText("Display Prices");
        WelcDispPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcDispPricesButtonActionPerformed(evt);
            }
        });

        WelcEditPricesButton.setText("Edit Prices");
        WelcEditPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcEditPricesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeWindowLayout = new javax.swing.GroupLayout(WelcomeWindow);
        WelcomeWindow.setLayout(WelcomeWindowLayout);
        WelcomeWindowLayout.setHorizontalGroup(
            WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeWindowLayout.createSequentialGroup()
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(WelcomeWindowLayout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabelWW, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(WelcomeWindowLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WelcDispPricesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WelcDispInvButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(69, 69, 69)
                        .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(WelcEditPricesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(WelcEditInvButton, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE))))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        WelcomeWindowLayout.setVerticalGroup(
            WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeWindowLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabelWW, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcEditInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcDispInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcDispPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcEditPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        DynamicPanel.add(WelcomeWindow, "card2");

        DisplayPrices.setBackground(new java.awt.Color(255, 51, 51));

        jTextAreaDP.setColumns(20);
        jTextAreaDP.setRows(5);
        jTextAreaDP.setText("Inventory Prints Here:");
        jScrollPane2.setViewportView(jTextAreaDP);

        jLabelDP.setFont(new java.awt.Font("Lemon/Milk", 0, 18)); // NOI18N
        jLabelDP.setText("Display Prices");

        javax.swing.GroupLayout DisplayPricesLayout = new javax.swing.GroupLayout(DisplayPrices);
        DisplayPrices.setLayout(DisplayPricesLayout);
        DisplayPricesLayout.setHorizontalGroup(
            DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPricesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDP)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(132, Short.MAX_VALUE))
        );
        DisplayPricesLayout.setVerticalGroup(
            DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPricesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelDP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        DynamicPanel.add(DisplayPrices, "card3");

        DisplayInventory.setBackground(new java.awt.Color(153, 255, 255));
        DisplayInventory.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        jLabel2.setText("Display Inventory");

        textAreaDis.setColumns(20);
        textAreaDis.setRows(5);
        jScrollPane3.setViewportView(textAreaDis);

        javax.swing.GroupLayout DisplayInventoryLayout = new javax.swing.GroupLayout(DisplayInventory);
        DisplayInventory.setLayout(DisplayInventoryLayout);
        DisplayInventoryLayout.setHorizontalGroup(
            DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayInventoryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 609, Short.MAX_VALUE)
                    .addGroup(DisplayInventoryLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DisplayInventoryLayout.setVerticalGroup(
            DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                .addContainerGap())
        );

        DynamicPanel.add(DisplayInventory, "card7");

        EditInv.setBackground(new java.awt.Color(255, 153, 255));
        EditInv.setForeground(new java.awt.Color(255, 255, 255));

        EditInvLabel.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        EditInvLabel.setText("Edit Inventory");

        jEditInvList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jEditInvList);

        javax.swing.GroupLayout EditInvLayout = new javax.swing.GroupLayout(EditInv);
        EditInv.setLayout(EditInvLayout);
        EditInvLayout.setHorizontalGroup(
            EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditInvLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(EditInvLabel)
                .addContainerGap(249, Short.MAX_VALUE))
        );
        EditInvLayout.setVerticalGroup(
            EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditInvLayout.createSequentialGroup()
                .addGroup(EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditInvLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(EditInvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(EditInvLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        DynamicPanel.add(EditInv, "card7");

        EditPrices.setBackground(new java.awt.Color(255, 153, 153));

        jEditPriceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jEditPriceList);

        SelectItemButton.setText("Select Item");
        SelectItemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectItemButtonActionPerformed(evt);
            }
        });

        jProductLabel.setText("Product");

        jPriceLabel.setText("Price");

        SavePriceButton.setText("Save");
        SavePriceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavePriceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout EditPricesLayout = new javax.swing.GroupLayout(EditPrices);
        EditPrices.setLayout(EditPricesLayout);
        EditPricesLayout.setHorizontalGroup(
            EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPricesLayout.createSequentialGroup()
                .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProductLabel)
                            .addComponent(jPriceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdTextField)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SavePriceButton)))
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(SelectItemButton)))
                .addContainerGap(188, Short.MAX_VALUE))
        );
        EditPricesLayout.setVerticalGroup(
            EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPricesLayout.createSequentialGroup()
                .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addContainerGap(42, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProductLabel)
                            .addComponent(ProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPriceLabel)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(SavePriceButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(SelectItemButton)
                .addGap(38, 38, 38))
        );

        DynamicPanel.add(EditPrices, "card8");

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DispInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispInvButtonActionPerformed
        p = DisplayInventory;
        ChangePanel();
        DisplayInventory();
    }//GEN-LAST:event_DispInvButtonActionPerformed

    private void DispPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispPricesButtonActionPerformed
        // Sets indicator to selected frame and changes the panel to it
        p = DisplayPrices;
        ChangePanel();
        DisplayPrices();
    }//GEN-LAST:event_DispPricesButtonActionPerformed

    private void EditPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPricesButtonActionPerformed
        // Sets indicator to selected frame and changes the panel to it
        p = EditPrices;
        ChangePanel();
        DisplayList();
        jEditPriceList.setModel(model1);
    }//GEN-LAST:event_EditPricesButtonActionPerformed

    private void WelcDispInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcDispInvButtonActionPerformed
        p = DisplayInventory;
        ChangePanel();
        DisplayInventory();
    }//GEN-LAST:event_WelcDispInvButtonActionPerformed

    private void WelcDispPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcDispPricesButtonActionPerformed
        // Sets indicator to selected frame and changes the panel to it
        p = DisplayPrices;
        ChangePanel();
        DisplayPrices();
    }//GEN-LAST:event_WelcDispPricesButtonActionPerformed

    private void WelcEditPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcEditPricesButtonActionPerformed
        // Sets indicator to selected frame and changes the panel to it
        p = EditPrices;
        ChangePanel();
        DisplayList();
        jEditPriceList.setModel(model1);
    }//GEN-LAST:event_WelcEditPricesButtonActionPerformed

    private void EditInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInvButtonActionPerformed
       p = EditInv;
       ChangePanel();
       DisplayList();
       jEditInvList.setModel(model1);
    }//GEN-LAST:event_EditInvButtonActionPerformed

    private void SelectItemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectItemButtonActionPerformed
        // TODO add your handling code here:
        int i = jEditPriceList.getSelectedIndex();
        ProdTextField.setText(ItemList.get(i).getName());
        PriceTextField.setText(String.format("%1.2f", ItemList.get(i).getPrice()));
    }//GEN-LAST:event_SelectItemButtonActionPerformed

    private void WelcEditInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcEditInvButtonActionPerformed
        // TODO add your handling code here:
       p = EditInv;
       ChangePanel();
       DisplayList();
    }//GEN-LAST:event_WelcEditInvButtonActionPerformed

    private void SavePriceButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavePriceButtonActionPerformed
        // TODO add your handling code here:
        Double dHold = Double.parseDouble(PriceTextField.getText());
        int i = jEditPriceList.getSelectedIndex();
        ItemList.forEach((x) -> {        
            if (ItemList.indexOf(x) == i) {
                x.dPrice = dHold;
                System.out.println(x.dPrice);
            }
        }); 
        Save();
    }//GEN-LAST:event_SavePriceButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuDemo().setVisible(true);
//            }
//        });
        
        // create an instance of MainMenuDemo object
        // so we can use it to call non-static methods like ReadFile()
        // To learn more about static variables and methods work refer to
        // https://crunchify.com/java-static-methods-variables-static-block-and-class-with-example/
        MainMenuDemo object = new MainMenuDemo();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                object.setVisible(true);
            }
        });
        // Read file so arrays are preloaded with information.
        // Needed because you do not know which button the user will
        // press first
        object.ReadFile();
    }
    
    public void ChangePanel() {
        DynamicPanel.removeAll();
        DynamicPanel.add(p);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
    }

    public void DisplayPrices() {
        // Sets the text area to output the stored products and prices 
        PriceText = String.format("%-25s \t %-18s %n", "Item Name", "Price");
        PriceText += String.format("%-30s \t %-20s %n", "----------------", "--------");
        
        for (Item x: ItemList) {
            PriceText += String.format("%-28s \t %-18s %n %n", x.sName, x.dPrice);
            jTextAreaDP.setText(PriceText);
        }
        

        PriceText = "";
    }
    
    public void DisplayInventory() {
        // Sets the text area to output the stored products and prices 
        InvText = String.format("%-25s \t %-18s %n", "Item Name", "Quantity");
        InvText += String.format("%-30s \t %-20s %n", "----------------", "------------");

        ItemList.stream().map((x) -> {
            InvText += String.format("%-28s \t %-18s %n %n", x.sName, x.dStock);
            return x;
        }).forEach((_item) -> {
            textAreaDis.setText(InvText);
        });

        InvText = "";
    }

    public void ReadFile() {
        
         try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {

            while ((line = br.readLine()) != null) {
                // use comma as separator
                String[] inventory = line.split(cvsSplitBy);

                ItemList.add(new Item(inventory[0],Double.parseDouble(inventory[1]),Double.parseDouble(inventory[2])));
               
                System.out.println("||   "+ inventory[0] +" , "+ inventory[1] + " , " + inventory[2] + "    ||");
            }

        } catch (FileNotFoundException e) {
            System.out.println("file does not exist or could not be found.");
            System.err.println("FileNotFoundException: " + e.getMessage());
        } catch (IOException e) {
            System.out.println("Problem reading file.");
            System.out.println("IOException: " + e.getMessage());
        }
    }

    public void Save() {
        try {
            //Code in here must interact with buttons to edit file
            try (PrintWriter output = new PrintWriter(csvFile)) {
                //Code in here must interact with buttons to edit file
                ItemList.forEach((x) -> {
                    output.print(x.sName + "," + x.dPrice + "," + x.dStock + "\n");
                });
                output.close();
            }
            
        } catch (IOException ex) {
            System.out.format("ERROR; %s\n", ex);
        }
    }
    
    public void DisplayList() {
        model1.clear();
        ItemList.forEach((x) -> {
            model1.addElement(x.sName);
        }); 
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton DispInvButton;
    private javax.swing.JButton DispPricesButton;
    private javax.swing.JPanel DisplayInventory;
    private javax.swing.JPanel DisplayPrices;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel EditInv;
    private javax.swing.JButton EditInvButton;
    private javax.swing.JLabel EditInvLabel;
    private javax.swing.JPanel EditPrices;
    private javax.swing.JButton EditPricesButton;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JTextField ProdTextField;
    private javax.swing.JButton SavePriceButton;
    private javax.swing.JButton SelectItemButton;
    private javax.swing.JButton WelcDispInvButton;
    private javax.swing.JButton WelcDispPricesButton;
    private javax.swing.JButton WelcEditInvButton;
    private javax.swing.JButton WelcEditPricesButton;
    private javax.swing.JPanel WelcomeWindow;
    private javax.swing.JList<String> jEditInvList;
    private javax.swing.JList jEditPriceList;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDP;
    private javax.swing.JLabel jLabelWW;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jPriceLabel;
    private javax.swing.JLabel jProductLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaDP;
    private javax.swing.JTextArea textAreaDis;
    // End of variables declaration//GEN-END:variables
}
