/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.cptdemo;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.*;
import java.text.NumberFormat;
import javax.swing.DefaultListModel;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Edna
 */
public class MainMenuDemo extends javax.swing.JFrame {
    
    // Variables
    private javax.swing.JPanel p;

    String PriceText = "";
    String InvText = "";
    String PriceHeader;
    String price;
    int i;

    String[] sItems = new String[14];
    Double[][] dValues = new Double[2][14];
    FileReader in;
    BufferedReader readFile;
    String lineOfText;
    String File = "StockList.txt";
    String[] inventory;

    String csvFile = "StockList.csv";
    String line = "";
    String cvsSplitBy = ",";
    List<Item> ItemList = new ArrayList<Item>();
    
    // Format numeric values to two decimal places and currency
    public static NumberFormat money = NumberFormat.getCurrencyInstance();

    /**
     * Creates new form MainMenuDemo
     */
    public MainMenuDemo() {
        initComponents();
        
       
        
       // readPrintDisplay.append(file.fileRead() + newline);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonsPanel = new javax.swing.JPanel();
        DispInvButton = new javax.swing.JButton();
        EditInvButton = new javax.swing.JButton();
        DispPricesButton = new javax.swing.JButton();
        EditPricesButton = new javax.swing.JButton();
        DynamicPanel = new javax.swing.JPanel();
        WelcomeWindow = new javax.swing.JPanel();
        jLabelWW = new javax.swing.JLabel();
        WelcDispInvButton = new javax.swing.JButton();
        WelcEditInvButton = new javax.swing.JButton();
        WelcDispPricesButton = new javax.swing.JButton();
        WelcEditPricesButton = new javax.swing.JButton();
        DisplayPrices = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaDP = new javax.swing.JTextArea();
        jLabelDP = new javax.swing.JLabel();
        DisplayInventory = new javax.swing.JPanel();
        DispInvLabel = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        textAreaDis = new javax.swing.JTextArea();
        EditInv = new javax.swing.JPanel();
        EditInvLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jEditInvList = new javax.swing.JList<>();
        EditPrices = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jEditPriceList = new javax.swing.JList();
        SelectItemEPButton = new javax.swing.JButton();
        jProductLabel = new javax.swing.JLabel();
        ProdTextField = new javax.swing.JTextField();
        jPriceLabel = new javax.swing.JLabel();
        PriceTextField = new javax.swing.JTextField();
        SavePriceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        jMenuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        DispInvButton.setText("Display Inventory");
        DispInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispInvButtonActionPerformed(evt);
            }
        });

        EditInvButton.setText("Edit Inventory");
        EditInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditInvButtonActionPerformed(evt);
            }
        });

        DispPricesButton.setText("Display Prices");
        DispPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DispPricesButtonActionPerformed(evt);
            }
        });

        EditPricesButton.setText("Edit Prices");
        EditPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditPricesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ButtonsPanelLayout = new javax.swing.GroupLayout(ButtonsPanel);
        ButtonsPanel.setLayout(ButtonsPanelLayout);
        ButtonsPanelLayout.setHorizontalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ButtonsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(ButtonsPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(DispInvButton))
                    .addComponent(EditInvButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(DispPricesButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EditPricesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        ButtonsPanelLayout.setVerticalGroup(
            ButtonsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(DispInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(DispPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(EditPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        DynamicPanel.setBackground(new java.awt.Color(255, 51, 255));
        DynamicPanel.setLayout(new java.awt.CardLayout());

        WelcomeWindow.setBackground(new java.awt.Color(153, 255, 255));

        jLabelWW.setFont(new java.awt.Font("Lemon/Milk", 0, 24)); // NOI18N
        jLabelWW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWW.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my/cptdemo/Tuck 'N' Roll Logo.png"))); // NOI18N

        WelcDispInvButton.setText("Display Inventory");
        WelcDispInvButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcDispInvButtonActionPerformed(evt);
            }
        });

        WelcEditInvButton.setText("Edit Inventory");

        WelcDispPricesButton.setText("Display Prices");
        WelcDispPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcDispPricesButtonActionPerformed(evt);
            }
        });

        WelcEditPricesButton.setText("Edit Prices");
        WelcEditPricesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WelcEditPricesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout WelcomeWindowLayout = new javax.swing.GroupLayout(WelcomeWindow);
        WelcomeWindow.setLayout(WelcomeWindowLayout);
        WelcomeWindowLayout.setHorizontalGroup(
            WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeWindowLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeWindowLayout.createSequentialGroup()
                        .addComponent(WelcDispPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(WelcEditPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeWindowLayout.createSequentialGroup()
                        .addComponent(WelcDispInvButton)
                        .addGap(114, 114, 114)
                        .addComponent(WelcEditInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, WelcomeWindowLayout.createSequentialGroup()
                .addContainerGap(201, Short.MAX_VALUE)
                .addComponent(jLabelWW, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(162, 162, 162))
        );
        WelcomeWindowLayout.setVerticalGroup(
            WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(WelcomeWindowLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelWW, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcDispInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcEditInvButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(WelcomeWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(WelcEditPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(WelcDispPricesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        DynamicPanel.add(WelcomeWindow, "card2");

        DisplayPrices.setBackground(new java.awt.Color(153, 255, 255));

        jTextAreaDP.setColumns(20);
        jTextAreaDP.setRows(5);
        jTextAreaDP.setText("Inventory Prints Here:");
        jScrollPane2.setViewportView(jTextAreaDP);

        jLabelDP.setFont(new java.awt.Font("BubbleGum", 0, 36)); // NOI18N
        jLabelDP.setText("Display Prices");

        javax.swing.GroupLayout DisplayPricesLayout = new javax.swing.GroupLayout(DisplayPrices);
        DisplayPrices.setLayout(DisplayPricesLayout);
        DisplayPricesLayout.setHorizontalGroup(
            DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPricesLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDP)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(464, Short.MAX_VALUE))
        );
        DisplayPricesLayout.setVerticalGroup(
            DisplayPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayPricesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelDP)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                .addContainerGap())
        );

        DynamicPanel.add(DisplayPrices, "card3");

        DisplayInventory.setBackground(new java.awt.Color(153, 255, 255));
        DisplayInventory.setForeground(new java.awt.Color(255, 255, 255));

        DispInvLabel.setFont(new java.awt.Font("BubbleGum", 0, 36)); // NOI18N
        DispInvLabel.setText("Display Inventory");

        textAreaDis.setColumns(20);
        textAreaDis.setRows(5);
        jScrollPane3.setViewportView(textAreaDis);

        javax.swing.GroupLayout DisplayInventoryLayout = new javax.swing.GroupLayout(DisplayInventory);
        DisplayInventory.setLayout(DisplayInventoryLayout);
        DisplayInventoryLayout.setHorizontalGroup(
            DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayInventoryLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 941, Short.MAX_VALUE)
                    .addGroup(DisplayInventoryLayout.createSequentialGroup()
                        .addComponent(DispInvLabel)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DisplayInventoryLayout.setVerticalGroup(
            DisplayInventoryLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DisplayInventoryLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DispInvLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE)
                .addContainerGap())
        );

        DynamicPanel.add(DisplayInventory, "card7");

        EditInv.setBackground(new java.awt.Color(153, 255, 255));
        EditInv.setForeground(new java.awt.Color(255, 255, 255));

        EditInvLabel.setFont(new java.awt.Font("BubbleGum", 0, 36)); // NOI18N
        EditInvLabel.setText("Edit Inventory");

        jEditInvList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(jEditInvList);

        javax.swing.GroupLayout EditInvLayout = new javax.swing.GroupLayout(EditInv);
        EditInv.setLayout(EditInvLayout);
        EditInvLayout.setHorizontalGroup(
            EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditInvLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EditInvLabel)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(675, Short.MAX_VALUE))
        );
        EditInvLayout.setVerticalGroup(
            EditInvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditInvLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(EditInvLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        DynamicPanel.add(EditInv, "card7");

        EditPrices.setBackground(new java.awt.Color(153, 255, 255));

        jEditPriceList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jEditPriceList);

        SelectItemEPButton.setText("Select Item");
        SelectItemEPButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectItemEPButtonActionPerformed(evt);
            }
        });

        jProductLabel.setText("Product");

        jPriceLabel.setText("Price");

        SavePriceButton.setText("Save");

        jLabel1.setFont(new java.awt.Font("BubbleGum", 0, 36)); // NOI18N
        jLabel1.setText("Edit Prices");

        javax.swing.GroupLayout EditPricesLayout = new javax.swing.GroupLayout(EditPrices);
        EditPrices.setLayout(EditPricesLayout);
        EditPricesLayout.setHorizontalGroup(
            EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPricesLayout.createSequentialGroup()
                .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(SelectItemEPButton))
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jProductLabel)
                            .addComponent(jPriceLabel))
                        .addGap(18, 18, 18)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ProdTextField)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SavePriceButton)))
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(520, Short.MAX_VALUE))
        );
        EditPricesLayout.setVerticalGroup(
            EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EditPricesLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jProductLabel)
                            .addComponent(ProdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(EditPricesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPriceLabel)
                            .addComponent(PriceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(48, 48, 48)
                        .addComponent(SavePriceButton))
                    .addGroup(EditPricesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(SelectItemEPButton)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        DynamicPanel.add(EditPrices, "card8");

        MenuFile.setText("File");
        MenuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFileActionPerformed(evt);
            }
        });

        jMenuExit.setText("Exit");
        jMenuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuExitActionPerformed(evt);
            }
        });
        MenuFile.add(jMenuExit);

        jMenuBar1.add(MenuFile);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(ButtonsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DynamicPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DispInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispInvButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = DisplayInventory;
        ChangePanel();
        DisplayInventory();
    }//GEN-LAST:event_DispInvButtonActionPerformed

    private void MenuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFileActionPerformed

    }//GEN-LAST:event_MenuFileActionPerformed

    private void jMenuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuExitActionPerformed
        // Exits program safely when clicked
        System.exit(0);
    }//GEN-LAST:event_jMenuExitActionPerformed

    private void DispPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DispPricesButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = DisplayPrices;
        ChangePanel();
        DisplayPrices();
    }//GEN-LAST:event_DispPricesButtonActionPerformed

    private void EditPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditPricesButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = EditPrices;
        ChangePanel();
        jListEditPrices();
    }//GEN-LAST:event_EditPricesButtonActionPerformed

    private void WelcDispInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcDispInvButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = DisplayInventory;
        ChangePanel();
        DisplayInventory();
    }//GEN-LAST:event_WelcDispInvButtonActionPerformed

    private void WelcDispPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcDispPricesButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = DisplayPrices;
        ChangePanel();
        DisplayPrices();
    }//GEN-LAST:event_WelcDispPricesButtonActionPerformed

    private void WelcEditPricesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WelcEditPricesButtonActionPerformed
        // Sets Dynamic Panel to selected panel & performs action of that panel
        p = EditPrices;
        ChangePanel();
        jListEditPrices();
    }//GEN-LAST:event_WelcEditPricesButtonActionPerformed

    private void EditInvButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditInvButtonActionPerformed
       p = EditInv;
       ChangePanel();
       DefaultListModel model1 = new DefaultListModel();
        for (String sItem: sItems) {
            model1.addElement(sItem);
        }
        jEditInvList.setModel(model1);
    }//GEN-LAST:event_EditInvButtonActionPerformed

    private void SelectItemEPButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectItemEPButtonActionPerformed
        // Identifies product choice from jList and displays related values in their fields
        int i = jEditPriceList.getSelectedIndex();
        ProdTextField.setText(sItems[i]);
        PriceTextField.setText(String.format("%1.2f", dValues[0][i]));
    }//GEN-LAST:event_SelectItemEPButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainMenuDemo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainMenuDemo().setVisible(true);
//            }
//        });
        
        // create an instance of MainMenuDemo object
        // so we can use it to call non-static methods like ReadFile()
        // To learn more about static variables and methods work refer to
        // https://crunchify.com/java-static-methods-variables-static-block-and-class-with-example/
        MainMenuDemo object = new MainMenuDemo();
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                object.setVisible(true);
            }
        });
      
        // read file so arrays are preloaded with information.
        // Needed because you do not know which button the user will
        // press first
        object.ReadFile();
        object.showFileContents();
    
    
    }
    
    public void showFileContents() {
        System.out.println("sItems Contents:");
        for (int x = 0; x < sItems.length; x++) {
            System.out.print(sItems[x] + ",");
        }

        System.out.println("dValues Contents:");
        for (int x = 0; x < dValues.length; x++) {
            for (int y = 0; y < dValues[x].length; y++) {
                System.out.print(dValues[x][y] + ",");
            }
        }
    }
    
    public void ChangePanel() {
        // Changes the status of the dynamic panel to the selection and SMTH ABOUT SAVE
        DynamicPanel.removeAll();
        DynamicPanel.add(p);
        DynamicPanel.repaint();
        DynamicPanel.revalidate();
        Save();
    }

    public void DisplayPrices() {
        // Sets the textarea to output the stored products and prices 
        PriceText = String.format("%-25s \t %-18s %n", "Item Name", "Price");
        PriceText += String.format("%-30s \t %-20s %n", "----------------", "--------");

        for (int x = 0; x < sItems.length; x++) {
            PriceText += String.format("%-28s \t %-18s %n %n", sItems[x], dValues[0][x]);
            jTextAreaDP.setText(PriceText);
        }
        PriceText = "";
    }
    
    public void DisplayInventory() {
        // Sets the textarea to output the stored products and quantities 
        InvText = String.format("%-25s \t %-18s %n", "Item Name", "Quantity");
        InvText += String.format("%-30s \t %-20s %n", "----------------", "------------");

        for (int x = 0; x < sItems.length; x++) {
            InvText += String.format("%-28s \t %-18s %n %n", sItems[x], dValues[1][x]);
            textAreaDis.setText(InvText);
        }

        InvText = "";
    }

    public void EditPrices() {
        // Use this for the actual editing
    }
    
    public void jListEditPrices() {
        // Creates an instance of jList and displays the products in the list
        DefaultListModel model1 = new DefaultListModel();
        for (String sItem: sItems) {
            model1.addElement(sItem);
        }
        jEditPriceList.setModel(model1);
    }

    public void ReadFile() {
        File textFile = new File(File);
        
         try (BufferedReader br = new BufferedReader(new FileReader(csvFile))) {

            while ((line = br.readLine()) != null) {
                int count = 0;
                // use comma as separator
                String[] inventory = line.split(cvsSplitBy);

                ItemList.add(new Item(inventory[0],Double.parseDouble(inventory[1]),Double.parseDouble(inventory[2])));
               
               
                System.out.println("||   "+ inventory[0] +" , "+ inventory[1] + " , " + inventory[2] + "    ||");
                count++;
            }

        } catch (IOException e) {
            e.printStackTrace();
        }
/*
        try {
            in = new FileReader(textFile);
            readFile = new BufferedReader(in);
            for (int i = 0; i < sItems.length; i++) {
                lineOfText = readFile.readLine();

                sItems[i] = lineOfText;
                System.out.println(sItems[i]);
            }
            for (Double[] dValue : dValues) {
                for (int c = 0; c < dValue.length; c++) {
                    lineOfText = readFile.readLine();
                    Double dNum = Double.parseDouble(lineOfText);
                    dValue[c] = dNum;
                    System.out.println(dValue[c]);
                }
            }

            readFile.close();
            in.close();

        } catch (FileNotFoundException e) {
            System.out.println("file does not exist or could not be found.");
            System.err.println("FileNotFoundException: " + e.getMessage());
        } catch (IOException e) {
            System.out.println("Problem reading file.");
            System.out.println("IOException: " + e.getMessage());
        }*/
    }

    public void Save() {
        try {
            //Code in here must interact with buttons to edit file
            try (PrintWriter output = new PrintWriter(File)) {
                //Code in here must interact with buttons to edit file
                for (String sItem : sItems) {
                    output.println(sItem);
                }
                for (Double[] dValue : dValues) {
                    for (Double dValue1 : dValue) {
                        output.println(dValue1);
                    }
                }
                output.close();
            }
        } catch (IOException ex) {
            System.out.format("ERROR; %s\n", ex);
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ButtonsPanel;
    private javax.swing.JButton DispInvButton;
    private javax.swing.JLabel DispInvLabel;
    private javax.swing.JButton DispPricesButton;
    private javax.swing.JPanel DisplayInventory;
    private javax.swing.JPanel DisplayPrices;
    private javax.swing.JPanel DynamicPanel;
    private javax.swing.JPanel EditInv;
    private javax.swing.JButton EditInvButton;
    private javax.swing.JLabel EditInvLabel;
    private javax.swing.JPanel EditPrices;
    private javax.swing.JButton EditPricesButton;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JTextField PriceTextField;
    private javax.swing.JTextField ProdTextField;
    private javax.swing.JButton SavePriceButton;
    private javax.swing.JButton SelectItemEPButton;
    private javax.swing.JButton WelcDispInvButton;
    private javax.swing.JButton WelcDispPricesButton;
    private javax.swing.JButton WelcEditInvButton;
    private javax.swing.JButton WelcEditPricesButton;
    private javax.swing.JPanel WelcomeWindow;
    private javax.swing.JList<String> jEditInvList;
    private javax.swing.JList jEditPriceList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDP;
    private javax.swing.JLabel jLabelWW;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuExit;
    private javax.swing.JLabel jPriceLabel;
    private javax.swing.JLabel jProductLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextAreaDP;
    private javax.swing.JTextArea textAreaDis;
    // End of variables declaration//GEN-END:variables
}
